spring:
  datasource:
    name: ax_shop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/flink_b?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true


flink:
  checkpoint-storage: /Users/xing/Desktop/flink-ck
  last: /d60d53151ee09168419e7fc17ea069fc/chk-12